# TENSORS
- 텐서란 array 나 matrics 와 흡사한 데이터 구조임
- 파이토치에선, 모델의 입력과 출력 또는 모델의 파라미터를 인코딩하기 위해 사용

- 텐서는 **NumPy의 array**와 흡사함
- 하지만 텐서는 **GPU**와 같은 연산 가속기에서 동작할 수 있는 것이 차이점
- 텐서는 또한 **automatic differentiation** 을 통해 최적화됨

In [1]:
import torch
import numpy as np

---
# 1. Initializing a Tensor
- 텐서는 다양한 방법으로 초기화할 수 있음

## 1.1 Directly from data
- 이미 존재하는 데이터로부터 바로 텐서를 생성할 수 있음
- 데이터 타입은 자동으로 추정됨

In [4]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data, type(x_data), x_data.type(), x_data.shape, x_data.dtype)

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'> torch.LongTensor torch.Size([2, 2]) torch.int64


## 1.2 From a NumPy array
- **NumPy의 array** 로부터 생성할 수 있음

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np, type(x_np), x_np.type(), x_np.shape, x_np.dtype)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'> torch.IntTensor torch.Size([2, 2]) torch.int32


## 1.3 From another tensor
- 이미 존재하는 텐서의 특성(shape, datatype)을 유지하면서 새로운 텐서를 만들 수 있음

In [6]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand}")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6443, 0.5095],
        [0.1158, 0.4513]])


## 1.4 With random or constant values
- ```shape``` 는 텐서의 차원에 대한 튜플임
- 이는 출력 텐서의 차원을 결정함

In [7]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.4577, 0.4146, 0.2314],
        [0.7161, 0.0017, 0.5212]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



---
# 2. Attributes of a Tensor
- 텐서의 **attributes**는 그 텐서의 **shape, dtype, 저장된 device** 등의 정보를 알려줌

In [8]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device of tensor: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


---
# 3. Operations on Tensors
- arithmetic, linear algebra, matrix manipulation(전치, 인덱싱, 슬라이싱), sampling 등의 100개가 넘는 텐서 연산에 대한 정보를 홈페이지에서 확인 가능
- 각 연산은 GPU에서도 동작할 수 있음 (가끔은 CPU에서 더 빠르기도 함)

- 기본적으로 텐서는 CPU 상에 생성됨
- 그래서 텐서를 명시적으로 GPU 로 이동해줘야 함. 이때 ```.to``` 메서드를 이용
- 이때 매우 큰 텐서를 옮기는 작업은 시간과 메모리가 많이 필요하다는 것을 명심

In [9]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

## 3.1 Standard numpy-like indexing and slicing

In [10]:
tensor = torch.ones(4, 4)
print("First row: ", tensor[0])
print('First column: ', tensor[:, 0])
print('Last column: ', tensor[..., -1])

tensor[:, 1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## 3.2 Joining tensors
- ```torch.cat``` 을 이용해 주어진 텐서를 특정 차원에 따라 concatenate 할 수 있음
- ```torch.stack``` 도 참고할 것. 

In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


## 3.3 Arithmetic operations

In [15]:
# Matrix multiplication between two tensors

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print(y1)
print(y2)
print(y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [16]:
# Element-wise product

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z2)
print(z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## 3.4 Single-element tensors
- 텐서 내의 모든 값을 하나의 값으로 aggregating 하면서 1차원의 텐서를 생성할 수 있음
- 이때 ```item()``` 함수를 이용하여 그 값을 파이썬의 숫자로 변환할 수 있음

In [17]:
agg = tensor.sum()
agg_item = agg.item()
print(agg, agg_item, type(agg_item))

tensor(12.) 12.0 <class 'float'>


## 3.5 In-place operations
- 이름 끝에 ```_``` 가 붙으면 In-place 연산임
- 이 연산은 해당 텐서 자체를 바꿈

In [18]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


---
# 4. Bridge with NumPy
- CPU 상의 텐서와 NumPy의 array는 메모리 위치를 공유할 수 있음
- 따라서 그 중 하나를 수정하면 다른 하나도 수정됨

## 4.1 Tensor to NumPy array

In [19]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


- 텐서를 수정하면 NumPy array 에도 반영됨

In [20]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## 4.2 NumPy array to Tensor

In [21]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


In [22]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
